apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume1
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /tmp/data 