apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
spec:
  schedule: "*/1 * * * *"       # runs every 1 minute
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduled-message
              image: busybox
              command: ["sh", "-c", "date; echo 'CronJob executed!'"]
          restartPolicy: Never